version: '3'
services:
  postgres:
    image: lmmdock/postgres-multi
    restart: always
    environment:
      POSTGRES_USERS: pg-user:pg-password
      POSTGRES_DATABASES: srv_users:pg-user
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # Acts as API gateway, view the nginx conf file (services/nginx/nginx.conf)
  nginx:
    image: nginx:latest
    ports:
      - "8000:8080"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      #- ./services/frontend/public:/srv/www/static
    depends_on:
      - frontend
      - users

  frontend:
    build: ./services/frontend
    restart: always
    volumes:
      - ./services/frontend:/usr/app/src
    ports:
      - "3000:3000"

  users:
    build: ./services/users
    restart: always
    volumes:
      #- ./services/users:/usr/app
      - ../services/users:/usr/app
    ports:
      - "3001:3000"
    depends_on:
      - postgres
